### ISSUE TITLE
can't build futures-preview with the compat feature

### ISSUE THREAD

**Issue by bbigras** [kolloch/crate2nix#56]
Without the "compat" feature it builds.

crate2nix 0.6.1 (also tested with master, same issue)

**deps**
```toml
[dependencies]
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
```

**default.nix**
```nix
{ pkgsFn ? import <nixpkgs> }:

let
  mozOverlay = import (builtins.fetchTarball https://github.com/mozilla/nixpkgs-mozilla/archive/master.tar.gz);
  crateOverlay = self: super: {
    defaultCrateOverrides = super.defaultCrateOverrides // {
      test-crate2nix = _attrs: {
        buildInputs = with self; [];
      };
    };
  };
  pkgs = pkgsFn { overlays = [ mozOverlay crateOverlay ]; };
  buildRustCrate = pkgs.buildRustCrate.override {
    rustc = pkgs.latest.rustChannels.nightly.rust;
  };
in
  (pkgs.callPackage ./Cargo.nix { inherit buildRustCrate; })
```

**main.rs**
```rust
fn main() {
    println!("ok");
}
```

**build**
```
❯ nix-build default.nix
trace: root_crate is deprecated since crate2nix 0.4. Please use rootCrate instead.
trace: workspace_members is deprecated in crate2nix 0.4. Please use workspaceMembers instead.
these derivations will be built:
  /nix/store/8dnqvf22snjljh0lg2ddzfdrs4rfsg7m-rust_futures-util-preview-0.3.0-alpha.19.drv
  /nix/store/qc7w2a15139nszffq30j657c86kjnsxy-rust_futures-executor-preview-0.3.0-alpha.19.drv
  /nix/store/gpc6sdxik5fa3xaa1807b9b3mfmnrvx6-rust_futures-preview-0.3.0-alpha.19.drv
  /nix/store/lil53m4arbfq0iywws4xn3jc8786mgf1-rust_test-crate2nix-0.1.0.drv
building '/nix/store/8dnqvf22snjljh0lg2ddzfdrs4rfsg7m-rust_futures-util-preview-0.3.0-alpha.19.drv'...
unpacking sources
unpacking source archive /nix/store/hl7sx1fyz730rg6m5vhbafs2y662vb0r-futures-util-preview-0.3.0-alpha.19.tar.gz
source root is futures-util-preview-0.3.0-alpha.19.tar.gz
patching sources
configuring
building
Building src/lib.rs (futures_util)
Running rustc --crate-name futures_util src/lib.rs --crate-type lib -C opt-level=3 -C codegen-units=4 --edition 2018 -C metadata=bb515e6c5b -C extra-filename=-bb515e6c5b --cfg feature="alloc" --cfg feature="channel" --cfg feature="compat" --cfg feature="futures-channel-preview" --cfg feature="futures-core-preview/alloc" --cfg feature="futures-core-preview/std" --cfg feature="futures-io-preview" --cfg feature="futures-sink-preview" --cfg feature="futures_01" --cfg feature="io" --cfg feature="memchr" --cfg feature="sink" --cfg feature="slab" --cfg feature="std" --out-dir target/lib --emit=dep-info,link -L dependency=target/deps --extern futures_channel=/nix/store/n56bbbia4i6gskgazv5g0cdv5mr1dvjf-rust_futures-channel-preview-0.3.0-alpha.19/lib/libfutures_channel-b463852d05.rlib --extern futures_core=/nix/store/54ackc3z5y3xy6m5zdsrzgf8v8cb76f0-rust_futures-core-preview-0.3.0-alpha.19/lib/libfutures_core-d44a134ac6.rlib --extern futures_io=/nix/store/mj49lgarg8f30cbk7wpfhv7bkhqbacqc-rust_futures-io-preview-0.3.0-alpha.19/lib/libfutures_io-04d6d753fb.rlib --extern futures_sink=/nix/store/01nn9cmicvp75q13zdwh1fbgbcwj5gk4-rust_futures-sink-preview-0.3.0-alpha.19/lib/libfutures_sink-e9750fb7dd.rlib --extern memchr=/nix/store/hfszhpn12gvakbpgsqdmw7kifnv3q5yh-rust_memchr-2.2.1/lib/libmemchr-ed1427d978.rlib --extern pin_utils=/nix/store/qvs9ryxqagqmpin66g1rhpmx1bazzqjb-rust_pin-utils-0.1.0-alpha.4/lib/libpin_utils-f799508eca.rlib --extern slab=/nix/store/0ms1yan0n2dnjl93p9h8lycdphq3hjd6-rust_slab-0.4.2/lib/libslab-d13bd9d52c.rlib --cap-lints allow --color always
error[E0433]: failed to resolve: use of undeclared type or module `futures_01`
 --> src/compat/executor.rs:9:5
  |
9 | use futures_01::future::{Executor as Executor01, ExecuteError as ExecuteError01};
  |     ^^^^^^^^^^ use of undeclared type or module `futures_01`

error[E0433]: failed to resolve: use of undeclared type or module `futures_01`
 --> src/compat/compat01as03.rs:1:5
  |
1 | use futures_01::executor::{
  |     ^^^^^^^^^^ use of undeclared type or module `futures_01`

error[E0432]: unresolved import `futures_01`
 --> src/compat/executor.rs:8:5
  |
8 | use futures_01::Future as Future01;
  |     ^^^^^^^^^^ use of undeclared type or module `futures_01`

error[E0432]: unresolved import `futures_01`
 --> src/compat/compat01as03.rs:5:5
  |
5 | use futures_01::{
  |     ^^^^^^^^^^ use of undeclared type or module `futures_01`

error[E0432]: unresolved import `futures_01`
  --> src/compat/compat01as03.rs:10:5
   |
10 | use futures_01::{AsyncSink as AsyncSink01, Sink as Sink01};
   |     ^^^^^^^^^^ use of undeclared type or module `futures_01`

error[E0432]: unresolved import `futures_01`
 --> src/compat/compat03as01.rs:1:5
  |
1 | use futures_01::{
  |     ^^^^^^^^^^ use of undeclared type or module `futures_01`

error[E0432]: unresolved import `futures_01`
 --> src/compat/compat03as01.rs:6:5
  |
6 | use futures_01::{
  |     ^^^^^^^^^^ use of undeclared type or module `futures_01`

error[E0433]: failed to resolve: use of undeclared type or module `NotifyHandle01`
   --> src/compat/compat01as03.rs:347:18
    |
347 |         unsafe { NotifyHandle01::new(Box::into_raw(ptr)) }
    |                  ^^^^^^^^^^^^^^ use of undeclared type or module `NotifyHandle01`

error[E0405]: cannot find trait `Executor01` in this scope
  --> src/compat/executor.rs:18:32
   |
18 | pub trait Executor01CompatExt: Executor01<Executor01Future> +
   |                                ^^^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `Executor01` in this scope
  --> src/compat/executor.rs:51:11
   |
51 | where Ex: Executor01<Executor01Future> + Clone + Send + 'static
   |           ^^^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `Executor01` in this scope
  --> src/compat/executor.rs:69:9
   |
69 |     Ex: Executor01<Executor01Future> + Clone + Send + 'static,
   |         ^^^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `Executor01` in this scope
  --> src/compat/executor.rs:84:15
   |
84 | impl<Sp, Fut> Executor01<Fut> for Compat<Sp>
   |               ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `ExecuteError01` in this scope
  --> src/compat/executor.rs:89:50
   |
89 |     fn execute(&self, future: Fut) -> Result<(), ExecuteError01<Fut>> {
   |                                                  ^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `Spawn01` in this scope
  --> src/compat/compat01as03.rs:26:23
   |
26 |     pub(crate) inner: Spawn01<T>,
   |                       ^^^^^^^ not found in this scope

error[E0425]: cannot find function `spawn01` in this scope
  --> src/compat/compat01as03.rs:36:20
   |
36 |             inner: spawn01(object),
   |                    ^^^^^^^ not found in this scope

error[E0412]: cannot find type `Spawn01` in this scope
   --> src/compat/compat01as03.rs:186:23
    |
186 |     pub(crate) inner: Spawn01<S>,
    |                       ^^^^^^^ not found in this scope

error[E0425]: cannot find function `spawn01` in this scope
   --> src/compat/compat01as03.rs:199:20
    |
199 |             inner: spawn01(inner),
    |                    ^^^^^^^ not found in this scope

error[E0412]: cannot find type `NotifyHandle01` in this scope
   --> src/compat/compat01as03.rs:343:34
    |
343 | impl From<WakerToHandle<'_>> for NotifyHandle01 {
    |                                  ^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `NotifyHandle01` in this scope
   --> src/compat/compat01as03.rs:344:43
    |
344 |     fn from(handle: WakerToHandle<'_>) -> NotifyHandle01 {
    |                                           ^^^^^^^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `Notify01` in this scope
   --> src/compat/compat01as03.rs:351:6
    |
351 | impl Notify01 for NotifyWaker {
    |      ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `UnsafeNotify01` in this scope
   --> src/compat/compat01as03.rs:357:13
    |
357 | unsafe impl UnsafeNotify01 for NotifyWaker {
    |             ^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `NotifyHandle01` in this scope
   --> src/compat/compat01as03.rs:358:35
    |
358 |     unsafe fn clone_raw(&self) -> NotifyHandle01 {
    |                                   ^^^^^^^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `UnsafeNotify01` in this scope
   --> src/compat/compat01as03.rs:363:29
    |
363 |         let ptr: *const dyn UnsafeNotify01 = self;
    |                             ^^^^^^^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `UnsafeNotify01` in this scope
   --> src/compat/compat01as03.rs:364:44
    |
364 |         drop(Box::from_raw(ptr as *mut dyn UnsafeNotify01));
    |                                            ^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 24 previous errors

Some errors have detailed explanations: E0405, E0412, E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0405`.
builder for '/nix/store/8dnqvf22snjljh0lg2ddzfdrs4rfsg7m-rust_futures-util-preview-0.3.0-alpha.19.drv' failed with exit code 1
cannot build derivation '/nix/store/lil53m4arbfq0iywws4xn3jc8786mgf1-rust_test-crate2nix-0.1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/lil53m4arbfq0iywws4xn3jc8786mgf1-rust_test-crate2nix-0.1.0.drv' failed

```

```
❯ nix build -f Cargo.nix rootCrate.build
builder for '/nix/store/vfhpavldx7p87phmwcg2iyd7qfm4mkpf-rust_futures-util-preview-0.3.0-alpha.19.drv' failed with exit code 1; last 10 log lines:
  error[E0405]: cannot find trait `UnsafeNotify01` in this scope
     --> src/compat/compat01as03.rs:364:44
      |
  364 |         drop(Box::from_raw(ptr as *mut dyn UnsafeNotify01));
      |                                            ^^^^^^^^^^^^^^ not found in this scope

  error: aborting due to 24 previous errors

  Some errors have detailed explanations: E0405, E0412, E0425, E0432, E0433.
  For more information about an error, try `rustc --explain E0405`.
cannot build derivation '/nix/store/6wk2jgb3sgx04017vx7g33njgq1653fd-rust_test-crate2nix-0.1.0.drv': 1 dependencies couldn't be built
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/6wk2jgb3sgx04017vx7g33njgq1653fd-rust_test-crate2nix-0.1.0.drv' failed
```

**Comment by bbigras** [comment]
Any workaround/solution for this?

**Comment by kolloch** [comment]
Thanks for your report! I verified that it works on crate2nix-v0.7.0-alpha.7

**Comment by bbigras** [comment]
Yes it seems to work. Thanks!!
